import { useControlScope } from "@/contexts/ControlScopeContext";
import { formatMoney } from "@/lib/control";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, BadgeCheck, CircleDollarSign, Link2, ReceiptText, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { StatusPill } from "@/components/StatusPill";
import { Skeleton } from "@/components/ui/skeleton";

function MetricCard({ label, value, note, icon: Icon, tone }: { label: string; value: string; note: string; icon: typeof CircleDollarSign; tone: string }) { return <section className="soft-card rise-in rounded-3xl border bg-card p-5"><div className="flex items-start justify-between"><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-muted-foreground">{label}</p><div className={`grid size-9 place-items-center rounded-xl ${tone}`}><Icon className="size-[18px]" /></div></div><p className="money mt-5 text-2xl font-medium tracking-tight text-slate-900 sm:text-[1.7rem]">{value}</p><p className="mt-2 text-xs font-semibold text-muted-foreground">{note}</p></section>; }

export default function ControlDashboard() {
  const scope = useControlScope();
  const dashboard = trpc.control.dashboard.useQuery({ organisationId: scope.organisationId, branchId: scope.branchId });
  if (dashboard.isLoading) return <div className="space-y-6"><Skeleton className="h-28 rounded-3xl" /><div className="grid gap-4 md:grid-cols-3"><Skeleton className="h-36 rounded-3xl" /><Skeleton className="h-36 rounded-3xl" /><Skeleton className="h-36 rounded-3xl" /></div></div>;
  if (dashboard.isError) return <section className="rounded-3xl border border-rose-200 bg-rose-50 p-6"><ShieldAlert className="size-5 text-rose-700" /><h1 className="mt-3 font-extrabold">Control desk could not load</h1><p className="mt-1 text-sm text-rose-800">{dashboard.error.message}</p></section>;
  const data = dashboard.data!;
  return <div className="mx-auto max-w-7xl space-y-6"><section className="rise-in overflow-hidden rounded-[1.8rem] bg-[#071d22] p-6 text-white sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-teal-200">{scope.branchName} · Control desk</p><h1 className="mt-3 max-w-xl text-2xl font-extrabold tracking-tight sm:text-3xl">Decide from evidence, not assumptions.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">A scoped view of receivable position, recorded proof, deterministic matching, and operational exceptions.</p></div><div className="rounded-2xl border border-white/10 bg-white/6 px-4 py-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-teal-100/70">Reconciliation coverage</p><div className="mt-2 flex items-baseline gap-2"><span className="money text-2xl">{data.coverage.toFixed(2)}%</span><span className="text-xs text-slate-300">of in-scope position</span></div></div></div></section>
    <div className="grid gap-4 md:grid-cols-3"><MetricCard label="Receivable position" value={formatMoney(data.position.receivableMinor, data.position.currency)} note={`${data.counts.obligations} obligation${data.counts.obligations === 1 ? "" : "s"} in scope`} icon={CircleDollarSign} tone="bg-teal-50 text-teal-700" /><MetricCard label="Reconciled value" value={formatMoney(data.position.reconciledMinor, data.position.currency)} note={`${data.counts.recordedEvidence} recorded evidence event${data.counts.recordedEvidence === 1 ? "" : "s"}`} icon={Link2} tone="bg-sky-50 text-sky-700" /><MetricCard label="Needs attention" value={String(data.counts.unresolvedExceptions)} note="unresolved exception workload" icon={AlertTriangle} tone="bg-amber-50 text-amber-700" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="soft-card rounded-3xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><p className="text-sm font-extrabold">Priority exceptions</p><p className="mt-1 text-xs text-muted-foreground">Sorted by recorded urgency and status.</p></div><Link href="/exceptions" className="inline-flex items-center gap-1 text-xs font-extrabold text-teal-700 hover:text-teal-800">View all <ArrowRight className="size-3.5" /></Link></div>{data.priorityExceptions.length ? <div className="divide-y">{data.priorityExceptions.map(item => <div key={item.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700"><AlertTriangle className="size-[17px]" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.type.replaceAll("_", " ")} · due {item.dueAt ? new Date(item.dueAt).toLocaleDateString() : "not set"}</p></div><div className="flex items-center gap-3 sm:text-right"><span className="money text-sm font-medium">{formatMoney(item.valueImpactMinor, item.currency ?? data.position.currency)}</span><StatusPill status={item.status} /></div></div>)}</div> : <div className="px-5 py-12 text-center"><BadgeCheck className="mx-auto size-7 text-emerald-600" /><p className="mt-3 text-sm font-extrabold">No priority exceptions yet</p><p className="mt-1 text-xs text-muted-foreground">Record evidence and run reconciliation to surface exceptions that need review.</p></div>}</section>
      <section className="soft-card rounded-3xl border bg-card p-5"><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-muted-foreground">Control states</p><div className="mt-5 space-y-4"><div className="rounded-2xl bg-sky-50 p-4"><p className="text-sm font-extrabold text-sky-900">Recorded</p><p className="mt-1 text-xs leading-5 text-sky-800">Evidence exists with source provenance. It is not yet proof of settlement.</p></div><div className="rounded-2xl bg-teal-50 p-4"><p className="text-sm font-extrabold text-teal-900">Matched</p><p className="mt-1 text-xs leading-5 text-teal-800">A deterministic rule linked expected and observed records.</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-sm font-extrabold text-amber-900">Unresolved</p><p className="mt-1 text-xs leading-5 text-amber-800">A variance, delay, duplicate, or missing record still requires accountable action.</p></div></div><Link href="/receivables" className="mt-5 flex items-center justify-between rounded-2xl border px-4 py-3 text-sm font-extrabold hover:bg-slate-50">Review receivable records <ReceiptText className="size-4 text-teal-700" /></Link></section></div>
  </div>;
}
