import { useControlScope } from "@/contexts/ControlScopeContext";
import { formatMoney, getLiveValidationGuidance } from "@/lib/control";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, BadgeCheck, BookOpenCheck, Boxes, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardCheck, Link2, Network, ReceiptText, ShieldAlert, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { StatusPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useLanguage } from "@/contexts/LanguageContext";
import { useState } from "react";

function MetricCard({ label, value, note, icon: Icon, tone }: { label: string; value: string; note: string; icon: typeof CircleDollarSign; tone: string }) { return <section className="soft-card rise-in rounded-3xl border bg-card p-5"><div className="flex items-start justify-between"><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-muted-foreground">{label}</p><div className={`grid size-9 place-items-center rounded-xl ${tone}`}><Icon className="size-[18px]" /></div></div><p className="money mt-5 text-2xl font-medium tracking-tight text-slate-900 sm:text-[1.7rem]">{value}</p><p className="mt-2 text-xs font-semibold text-muted-foreground">{note}</p></section>; }

function RunStep({ number, title, copy, complete, href }: { number: number; title: string; copy: string; complete: boolean; href: string }) {
  return <Link href={href} className="group flex items-center gap-3 rounded-2xl border border-transparent px-3 py-3 transition-colors hover:border-teal-100 hover:bg-teal-50/50"><div className={`grid size-8 shrink-0 place-items-center rounded-xl text-xs font-extrabold ${complete ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{complete ? <CheckCircle2 className="size-4" /> : number}</div><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">{title}</p><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{copy}</p></div><ChevronRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-teal-700" /></Link>;
}

function ControlStage({ eyebrow, title, copy, href, icon: Icon, tone }: { eyebrow: string; title: string; copy: string; href: string; icon: typeof ReceiptText; tone: string }) {
  return <Link href={href} className="group flex min-w-0 items-start gap-3 rounded-2xl border bg-white p-3 transition-colors hover:border-teal-200 hover:bg-teal-50/40"><div className={`grid size-9 shrink-0 place-items-center rounded-xl ${tone}`}><Icon className="size-4" /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-muted-foreground">{eyebrow}</p><p className="mt-1 text-sm font-extrabold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{copy}</p></div><ChevronRight className="mt-1 size-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-teal-700" /></Link>;
}

export default function ControlDashboard() {
  const scope = useControlScope();
  const { t } = useLanguage();
  const dashboard = trpc.control.dashboard.useQuery({ organisationId: scope.organisationId, branchId: scope.branchId });
  const canViewPortfolio = ["owner", "controller"].includes(scope.role);
  const portfolio = trpc.control.variancePortfolio.useQuery({ organisationId: scope.organisationId }, { enabled: canViewPortfolio });
  const varianceAiPolicy = trpc.varianceAi.policy.get.useQuery(scope);
  const savedAiSuggestionQueue = trpc.varianceAi.suggestions.reviewQueue.useQuery(scope);
  const [varianceView, setVarianceView] = useState<"priority" | "ai">("priority");
  const savedAiSuggestionIds = new Set(savedAiSuggestionQueue.data?.map(item => item.exceptionId) ?? []);
  if (dashboard.isLoading) return <div className="space-y-6"><Skeleton className="h-28 rounded-3xl" /><div className="grid gap-4 md:grid-cols-3"><Skeleton className="h-36 rounded-3xl" /><Skeleton className="h-36 rounded-3xl" /><Skeleton className="h-36 rounded-3xl" /></div></div>;
  if (dashboard.isError) return <section className="rounded-3xl border border-rose-200 bg-rose-50 p-6"><ShieldAlert className="size-5 text-rose-700" /><h1 className="mt-3 font-extrabold">Control desk could not load</h1><p className="mt-1 text-sm text-rose-800">{dashboard.error.message}</p></section>;
  const data = dashboard.data!;
  const liveValidationGuidance = getLiveValidationGuidance(data.counts.recordedEvidence, data.counts.unresolvedExceptions);
  const nextAction = data.counts.unresolvedExceptions > 0
    ? { href: "/variances", label: "Review the priority variance", detail: "Resolve only the variance that needs accountable action." }
    : data.counts.obligations === 0
      ? { href: "/receivables", label: "Record the expected collection", detail: "Start with one customer and one receivable obligation." }
      : data.counts.recordedEvidence === 0
        ? { href: "/evidence", label: "Record independent evidence", detail: "Add a payment, settlement, or delivery observation with its source reference." }
        : { href: "/evidence", label: "Run the next match", detail: "Open the recorded evidence and apply the deterministic matching rule." };
  const portfolioTotals = Object.entries(portfolio.data?.totals ?? {});
  const visiblePriorityExceptions = varianceView === "ai" ? data.priorityExceptions.filter(item => savedAiSuggestionIds.has(item.id)) : data.priorityExceptions;
  return <div className="mx-auto max-w-7xl space-y-6"><section className="rise-in overflow-hidden rounded-[1.8rem] bg-[#071d22] p-6 text-white sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-teal-200">{scope.branchName} · {t("controlDesk")}</p><h1 className="mt-3 max-w-xl text-2xl font-extrabold tracking-tight sm:text-3xl">{t("dashboardEvidenceTitle")}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{t("dashboardEvidenceCopy")}</p>{varianceAiPolicy.data?.enabled ? <Tooltip><TooltipTrigger asChild><Link href="/variances" className="mt-4 inline-flex w-fit items-center gap-2 rounded-full border border-violet-200/30 bg-violet-300/10 px-3 py-1.5 text-xs font-extrabold text-violet-100 transition-colors hover:bg-violet-300/20"><Sparkles className="size-3.5" /><span>{t("aiVarianceActive")}</span><span className="text-violet-200/85">· {t("aiVarianceActiveNote")}</span></Link></TooltipTrigger><TooltipContent className="max-w-xs text-xs leading-5">{t("aiBadgeTooltip")}</TooltipContent></Tooltip> : null}</div><div className="rounded-2xl border border-white/10 bg-white/6 px-4 py-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-teal-100/70">{t("reconciliationCoverage")}</p><div className="mt-2 flex items-baseline gap-2"><span className="money text-2xl">{data.coverage.toFixed(2)}%</span><span className="text-xs text-slate-300">of in-scope position</span></div></div></div></section>
    <div className="grid gap-4 md:grid-cols-3"><MetricCard label={t("receivablePosition")} value={formatMoney(data.position.receivableMinor, data.position.currency)} note={`${data.counts.obligations} obligation${data.counts.obligations === 1 ? "" : "s"} in scope`} icon={CircleDollarSign} tone="bg-teal-50 text-teal-700" /><MetricCard label={t("reconciledValue")} value={formatMoney(data.position.reconciledMinor, data.position.currency)} note={`${data.counts.recordedEvidence} recorded evidence event${data.counts.recordedEvidence === 1 ? "" : "s"}`} icon={Link2} tone="bg-sky-50 text-sky-700" /><MetricCard label={t("needsAttention")} value={String(data.counts.unresolvedExceptions)} note="unresolved exception workload" icon={AlertTriangle} tone="bg-amber-50 text-amber-700" /></div>
    {canViewPortfolio && portfolio.data ? <section className="soft-card overflow-hidden rounded-3xl border bg-card"><div className="flex flex-col gap-3 border-b px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-violet-50 text-violet-700"><Network className="size-5" /></div><div><p className="text-sm font-extrabold">Organisation variance watch</p><p className="mt-1 text-xs text-muted-foreground">Open variance totals across branches you are authorised to oversee.</p></div></div><div className="text-left sm:text-right"><p className="text-sm font-extrabold">{portfolio.data.openCount} open</p><p className="text-xs text-muted-foreground">{portfolio.data.visibility === "organisation" ? "organisation view" : "branch-limited view"}</p></div></div><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{portfolioTotals.length ? portfolioTotals.map(([currency, total]) => <div key={currency} className="rounded-2xl bg-violet-50/70 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-violet-700">Open value · {currency}</p><p className="money mt-2 text-xl font-medium text-violet-950">{formatMoney(total, currency)}</p></div>) : <p className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">No open variances in your authorised view.</p>}</div>{portfolio.data.branches.length ? <div className="border-t px-5 py-3"><div className="space-y-2">{portfolio.data.branches.map(branch => <div key={branch.branchId} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2 text-xs"><span className="min-w-0 truncate font-extrabold">{branch.branchName} <span className="font-mono text-muted-foreground">· {branch.branchCode}</span></span><span className="shrink-0 font-semibold text-slate-600">{branch.count} open · {Object.entries(branch.totals).map(([currency, total]) => formatMoney(total, currency)).join(" · ")}</span></div>)}</div></div> : null}</section> : null}
    <section className="soft-card rounded-3xl border bg-card p-5 sm:p-6"><div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-teal-50 text-teal-700"><ClipboardCheck className="size-5" /></div><div><p className="text-sm font-extrabold">{t("todayControlRun")}</p><p className="mt-1 text-xs text-muted-foreground">Four clear steps. The system keeps the trail; you focus only on the next decision.</p></div></div><Link href={nextAction.href} className="inline-flex items-center gap-1 text-xs font-extrabold text-teal-700 hover:text-teal-800">{nextAction.label} <ArrowRight className="size-3.5" /></Link></div><div className="mt-3 grid gap-2 lg:grid-cols-4"><RunStep number={1} title="Record expected value" copy="Capture the receivable once." complete={data.counts.obligations > 0} href="/receivables" /><RunStep number={2} title="Add independent proof" copy="Keep the source reference with it." complete={data.counts.recordedEvidence > 0} href="/evidence" /><RunStep number={3} title="Match deterministically" copy="Use the rule instead of a manual guess." complete={data.coverage > 0} href="/evidence" /><RunStep number={4} title="Resolve only variances" copy="No exception means no unnecessary work." complete={data.counts.unresolvedExceptions === 0 && data.counts.recordedEvidence > 0} href="/variances" /></div><p className="mt-4 rounded-xl bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-600"><span className="font-extrabold text-slate-800">Next action:</span> {nextAction.detail}</p></section>
    <section className="rounded-3xl border border-teal-100 bg-teal-50/40 p-5 sm:p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-teal-800">One accountable control chain</p><h2 className="mt-2 text-lg font-extrabold">{t("controlChain")}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-700">Each stage has its own truth boundary: an invoice is not payment, evidence is not settlement, and a prepared journal is not a posted entry.</p></div><p className="rounded-xl bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900"><span className="font-extrabold">{liveValidationGuidance.title}:</span> {liveValidationGuidance.message}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ControlStage eyebrow="Expected value & proof" title="Evidence control" copy="Record, match, and investigate only the variance." href="/evidence" icon={ReceiptText} tone="bg-sky-50 text-sky-700" /><ControlStage eyebrow="Stock & delivery" title="Operating facts" copy="Move from product and stock to invoice and follow-up." href="/operations" icon={Boxes} tone="bg-amber-50 text-amber-700" /><ControlStage eyebrow="Balanced consequence" title="Ledger posting" copy="Prepare and independently post balanced entries." href="/ledger" icon={BookOpenCheck} tone="bg-teal-50 text-teal-700" /><ControlStage eyebrow="Independent close" title="Period governance" copy="Define the window and close it independently." href="/ledger" icon={ClipboardCheck} tone="bg-violet-50 text-violet-700" /></div></section>
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="soft-card rounded-3xl border bg-card"><div className="flex flex-col gap-3 border-b px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-extrabold">{t("priorityExceptions")}</p><p className="mt-1 text-xs text-muted-foreground">Sorted by recorded urgency and status.</p></div><div className="flex items-center gap-2"><div className="flex rounded-xl bg-slate-100 p-1"><Button size="sm" variant={varianceView === "priority" ? "default" : "ghost"} className={varianceView === "priority" ? "h-7 rounded-lg bg-white px-2 text-[11px] text-slate-900 shadow-sm hover:bg-white" : "h-7 rounded-lg px-2 text-[11px]"} onClick={() => setVarianceView("priority")}>{t("allPriorityVariances")}</Button><Button size="sm" variant={varianceView === "ai" ? "default" : "ghost"} className={varianceView === "ai" ? "h-7 rounded-lg bg-violet-600 px-2 text-[11px] text-white hover:bg-violet-700" : "h-7 rounded-lg px-2 text-[11px]"} onClick={() => setVarianceView("ai")}>{t("savedAiSuggestions")} {savedAiSuggestionIds.size ? `(${savedAiSuggestionIds.size})` : ""}</Button></div><Link href="/variances" className="inline-flex items-center gap-1 text-xs font-extrabold text-teal-700 hover:text-teal-800">View all <ArrowRight className="size-3.5" /></Link></div></div>{visiblePriorityExceptions.length ? <div className="divide-y">{visiblePriorityExceptions.map(item => <div key={item.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700"><AlertTriangle className="size-[17px]" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.type.replaceAll("_", " ")} · due {item.dueAt ? new Date(item.dueAt).toLocaleDateString() : "not set"}</p></div><div className="flex items-center gap-3 sm:text-right"><span className="money text-sm font-medium">{formatMoney(item.valueImpactMinor, item.currency ?? data.position.currency)}</span><StatusPill status={item.status} /></div></div>)}</div> : <div className="px-5 py-12 text-center"><BadgeCheck className="mx-auto size-7 text-emerald-600" /><p className="mt-3 text-sm font-extrabold">{varianceView === "ai" ? t("noSavedAiSuggestions") : "No priority exceptions yet"}</p><p className="mt-1 text-xs text-muted-foreground">{varianceView === "ai" ? "Request an AI suggestion only when an authorised reviewer needs help investigating an open variance." : "Record evidence and run reconciliation to surface exceptions that need review."}</p></div>}</section>
      <section className="soft-card rounded-3xl border bg-card p-5"><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-muted-foreground">Control states</p><div className="mt-5 space-y-4"><div className="rounded-2xl bg-sky-50 p-4"><p className="text-sm font-extrabold text-sky-900">Recorded</p><p className="mt-1 text-xs leading-5 text-sky-800">Evidence exists with source provenance. It is not yet proof of settlement.</p></div><div className="rounded-2xl bg-teal-50 p-4"><p className="text-sm font-extrabold text-teal-900">Matched</p><p className="mt-1 text-xs leading-5 text-teal-800">A deterministic rule linked expected and observed records.</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-sm font-extrabold text-amber-900">Unresolved</p><p className="mt-1 text-xs leading-5 text-amber-800">A variance, delay, duplicate, or missing record still requires accountable action.</p></div></div><Link href="/receivables" className="mt-5 flex items-center justify-between rounded-2xl border px-4 py-3 text-sm font-extrabold hover:bg-slate-50">Review receivable records <ReceiptText className="size-4 text-teal-700" /></Link></section></div>
  </div>;
}
