import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useControlScope } from "@/contexts/ControlScopeContext";
import { formatMoney } from "@/lib/control";
import { downloadCsv, ledgerBalancesCsv, ledgerExportFilename, ledgerJournalEntriesCsv, type LedgerBalanceExportRow } from "@/lib/ledgerExport";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, BookOpenCheck, CircleAlert, Download, FilePlus2, Landmark, RotateCcw, Scale, Send, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const makeKey = () => crypto.randomUUID();
const canManageAccounts = (role: string) => ["owner", "controller"].includes(role);
const canPrepare = (role: string) => ["owner", "controller", "manager"].includes(role);
const canPost = (role: string) => ["owner", "controller", "approver"].includes(role);

type Account = { id: string; code: string; name: string; accountClass: string; normalBalance: string; isActive: number };
type Invoice = { id: string; invoiceNumber: string; amountMinor: string | number; currency: string; status: string };
type Journal = { id: string; sourceReference: string | null; sourceType: string; status: string; currency: string; memo: string; preparedByUserId: number; reversalOfJournalId: string | null; preparedAt: Date; postedAt: Date | null; lines: Array<{ id: string; debitMinor: string | number; creditMinor: string | number; accountId: string; memo?: string | null }>; decisions: Array<{ id: string; decision: string; rationale: string; createdAt: Date }> };

function Heading({ action }: { action?: React.ReactNode }) {
  return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-teal-700">Release 3 · economic consequence</p><h1 className="mt-2 text-2xl font-extrabold tracking-tight sm:text-3xl">Ledger control</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Prepare a balanced accounting consequence for a real issued invoice, then have someone else post it. Drafts do not change a receivable, payment, stock position, settlement, or exception.</p></div>{action}</div>;
}

function Status({ status }: { status: string }) {
  const palette = status === "posted" ? "bg-emerald-50 text-emerald-800" : status === "ready" ? "bg-amber-50 text-amber-900" : status === "reversed" ? "bg-violet-50 text-violet-800" : "bg-slate-100 text-slate-700";
  const copy = status === "ready" ? "ready for independent posting" : status;
  return <span className={`rounded-full px-2 py-1 text-[10px] font-extrabold uppercase tracking-wider ${palette}`}>{copy}</span>;
}

function AccountDialog() {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const create = trpc.ledger.accounts.create.useMutation({ onSuccess: () => { toast.success("Chart account recorded. It has no balance until a journal is independently posted."); setOpen(false); utils.ledger.accounts.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!canManageAccounts(scope.role)) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><Landmark className="mr-2 size-4" />Account</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add chart account</DialogTitle><DialogDescription>Use the account policy approved for this organisation. This only creates a scoped account definition; it does not create an opening balance or financial entry.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ ...scope, code: String(form.get("code")), name: String(form.get("name")), accountClass: String(form.get("accountClass")) as "asset" | "liability" | "equity" | "revenue" | "expense", normalBalance: String(form.get("normalBalance")) as "debit" | "credit", idempotencyKey: makeKey() }); }}><Input name="code" required minLength={2} maxLength={32} placeholder="Account code, e.g. 1100" /><Input name="name" required minLength={2} maxLength={160} placeholder="Account name, e.g. Trade receivables" /><div className="grid grid-cols-2 gap-3"><select name="accountClass" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="asset">Asset</option><option value="liability">Liability</option><option value="equity">Equity</option><option value="revenue">Revenue</option><option value="expense">Expense</option></select><select name="normalBalance" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="debit">Normal debit</option><option value="credit">Normal credit</option></select></div><Button disabled={create.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{create.isPending ? "Adding…" : "Add chart account"}</Button></form></DialogContent></Dialog>;
}

function PrepareInvoiceDialog({ invoices, accounts }: { invoices: Invoice[]; accounts: Account[] }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const prepare = trpc.ledger.journals.prepareInvoice.useMutation({ onSuccess: () => { toast.success("Balanced journal prepared. It now needs an independent posting decision."); setOpen(false); utils.ledger.journals.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!canPrepare(scope.role) || !invoices.length || accounts.filter(account => account.isActive).length < 2) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl bg-teal-700 hover:bg-teal-800"><FilePlus2 className="mr-2 size-4" />Prepare invoice journal</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Prepare invoice consequence</DialogTitle><DialogDescription>Choose the issued invoice and the organisation’s approved receivable and revenue accounts. The amount comes from the existing invoice. This creates a reviewable journal draft, not payment or settlement.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); prepare.mutate({ ...scope, invoiceId: String(form.get("invoiceId")), debitAccountId: String(form.get("debitAccountId")), creditAccountId: String(form.get("creditAccountId")), memo: String(form.get("memo")), rationale: String(form.get("rationale")), idempotencyKey: makeKey() }); }}><select name="invoiceId" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="" disabled>Select issued invoice</option>{invoices.filter(invoice => invoice.status === "issued").map(invoice => <option key={invoice.id} value={invoice.id}>{invoice.invoiceNumber} · {formatMoney(String(invoice.amountMinor), invoice.currency)}</option>)}</select><select name="debitAccountId" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="" disabled>Debit account</option>{accounts.filter(account => account.isActive).map(account => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select><select name="creditAccountId" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="" disabled>Credit account</option>{accounts.filter(account => account.isActive).map(account => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select><Input name="memo" required minLength={4} placeholder="What this invoice recognition represents" /><textarea name="rationale" required minLength={4} className="min-h-24 rounded-xl border bg-white p-3 text-sm" placeholder="Why this accounting consequence is appropriate" /><Button disabled={prepare.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{prepare.isPending ? "Preparing…" : "Prepare balanced journal"}</Button></form></DialogContent></Dialog>;
}

function PostDialog({ journal }: { journal: Journal }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const post = trpc.ledger.journals.post.useMutation({ onSuccess: () => { toast.success("Journal posted. Derived account balances are now updated."); setOpen(false); utils.ledger.journals.list.invalidate(scope); utils.ledger.accounts.balances.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!canPost(scope.role) || journal.status !== "ready") return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" className="rounded-lg bg-teal-700 text-xs hover:bg-teal-800"><Send className="mr-1.5 size-3.5" />Post</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Independently post journal</DialogTitle><DialogDescription>Posting is permanent in this workflow. Control Ledger checks the exact debit/credit balance, active accounts, scope, and that you did not prepare this source-linked journal.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); post.mutate({ ...scope, journalId: journal.id, rationale: String(form.get("rationale")), idempotencyKey: makeKey() }); }}><textarea name="rationale" required minLength={4} className="min-h-24 rounded-xl border bg-white p-3 text-sm" placeholder="Independent posting rationale" /><Button disabled={post.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{post.isPending ? "Posting…" : "Post balanced journal"}</Button></form></DialogContent></Dialog>;
}

function ReversalDialog({ journal }: { journal: Journal }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const reverse = trpc.ledger.journals.prepareReversal.useMutation({ onSuccess: () => { toast.success("Reversal journal prepared for independent posting. The original remains preserved."); setOpen(false); utils.ledger.journals.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!canPrepare(scope.role) || journal.status !== "posted") return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline" className="rounded-lg text-xs"><RotateCcw className="mr-1.5 size-3.5" />Reverse</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Prepare reversal</DialogTitle><DialogDescription>This creates an equal-and-opposite journal for independent posting. It does not edit or delete the original posted journal.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); reverse.mutate({ ...scope, journalId: journal.id, memo: String(form.get("memo")), rationale: String(form.get("rationale")), idempotencyKey: makeKey() }); }}><Input name="memo" required minLength={4} placeholder="Reason shown on the reversal journal" /><textarea name="rationale" required minLength={4} className="min-h-24 rounded-xl border bg-white p-3 text-sm" placeholder="Why an independent reversal is required" /><Button disabled={reverse.isPending} variant="outline" className="rounded-xl">{reverse.isPending ? "Preparing…" : "Prepare reversal"}</Button></form></DialogContent></Dialog>;
}

function LedgerCsvExports({ balances, journals, accounts }: { balances: LedgerBalanceExportRow[]; journals: Journal[]; accounts: Account[] }) {
  const scope = useControlScope();
  const exportBalances = () => { const exportedAt = new Date(); downloadCsv(ledgerExportFilename(scope, "balances", exportedAt), ledgerBalancesCsv(scope, balances, exportedAt)); toast.success("Ledger balance CSV downloaded."); };
  const exportJournals = () => { const exportedAt = new Date(); downloadCsv(ledgerExportFilename(scope, "journal-entries", exportedAt), ledgerJournalEntriesCsv(scope, journals, accounts, exportedAt)); toast.success("Ledger journal-entry CSV downloaded."); };
  return <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" className="rounded-xl" disabled={!balances.length} onClick={exportBalances}><Download className="mr-2 size-4" />Balances CSV</Button><Button type="button" variant="outline" className="rounded-xl" disabled={!journals.length} onClick={exportJournals}><Download className="mr-2 size-4" />Journals CSV</Button></div>;
}

function Empty({ icon: Icon, title, copy }: { icon: typeof BookOpenCheck; title: string; copy: string }) { return <div className="rounded-3xl border border-dashed bg-white/70 px-5 py-8 text-center"><div className="mx-auto grid size-10 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Icon className="size-5" /></div><p className="mt-3 text-sm font-extrabold">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-muted-foreground">{copy}</p></div>; }

export default function LedgerPage() {
  const scope = useControlScope(); const accountsQuery = trpc.ledger.accounts.list.useQuery(scope); const balancesQuery = trpc.ledger.accounts.balances.useQuery(scope); const journalsQuery = trpc.ledger.journals.list.useQuery(scope); const invoicesQuery = trpc.release2.invoices.list.useQuery(scope);
  const accounts = (accountsQuery.data ?? []) as Account[]; const balances = (balancesQuery.data ?? []) as LedgerBalanceExportRow[]; const invoices = (invoicesQuery.data ?? []) as Invoice[]; const journals = (journalsQuery.data ?? []) as Journal[];
  const failed = [accountsQuery, balancesQuery, journalsQuery, invoicesQuery].find(query => query.isError);
  if (failed?.isError) return <div className="mx-auto max-w-3xl space-y-6"><Heading /><section className="rounded-3xl border bg-white p-7 text-center shadow-sm"><CircleAlert className="mx-auto size-6 text-rose-600" /><p className="mt-3 text-sm font-extrabold text-rose-700">The ledger workspace could not load this scoped branch.</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{failed.error.message}</p><Button className="mt-5 rounded-xl" variant="outline" onClick={() => { accountsQuery.refetch(); balancesQuery.refetch(); journalsQuery.refetch(); invoicesQuery.refetch(); }}>Try again</Button></section></div>;
  const posted = journals.filter(journal => journal.status === "posted").length; const ready = journals.filter(journal => journal.status === "ready").length;
  return <div className="mx-auto max-w-7xl space-y-6"><Heading action={<div className="flex flex-wrap gap-2"><LedgerCsvExports balances={balances} journals={journals} accounts={accounts} /><AccountDialog /><PrepareInvoiceDialog invoices={invoices} accounts={accounts} /></div>} />
    <section className="grid gap-4 sm:grid-cols-3"><article className="rounded-3xl border bg-white p-5 shadow-sm"><Landmark className="size-5 text-teal-700" /><p className="mt-4 text-2xl font-extrabold">{accounts.length}</p><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Chart accounts</p></article><article className="rounded-3xl border bg-white p-5 shadow-sm"><Scale className="size-5 text-amber-700" /><p className="mt-4 text-2xl font-extrabold">{ready}</p><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Ready for independent posting</p></article><article className="rounded-3xl border bg-white p-5 shadow-sm"><BadgeCheck className="size-5 text-emerald-700" /><p className="mt-4 text-2xl font-extrabold">{posted}</p><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Posted journals</p></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Journal review queue</h2><p className="mt-1 text-xs text-muted-foreground">Prepared entries need an authorised person other than the preparer to post them.</p></div>{journalsQuery.isLoading ? <p className="p-5 text-sm text-muted-foreground">Loading journals…</p> : !journals.length ? <div className="p-5"><Empty icon={BookOpenCheck} title="No Release 3 journals" copy={accounts.length < 2 ? "Create the approved chart accounts first. No opening balances are created automatically." : "When an issued Release 2 invoice needs a ledger consequence, prepare it here for independent posting."} /></div> : <div className="divide-y">{journals.map(journal => <article key={journal.id} className="p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-extrabold">{journal.sourceReference ?? journal.sourceType}</p><Status status={journal.status} /></div><p className="mt-1 text-xs text-muted-foreground">{journal.sourceType.replaceAll("_", " ")} · prepared {new Date(journal.preparedAt).toLocaleString()}</p><p className="mt-2 text-xs leading-5 text-slate-600">{journal.memo}</p><div className="mt-3 flex flex-wrap gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground"><span>{journal.lines.length} balanced lines</span>{journal.reversalOfJournalId ? <span>reversal journal</span> : null}</div></div><div className="flex shrink-0 gap-2"><PostDialog journal={journal} /><ReversalDialog journal={journal} /></div></div></article>)}</div>}</div>
      <div className="space-y-6"><section className="rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Derived account balances</h2><p className="mt-1 text-xs text-muted-foreground">Only independently posted lines contribute here.</p></div>{balancesQuery.isLoading ? <p className="p-5 text-sm text-muted-foreground">Calculating posted balances…</p> : !balancesQuery.data?.length ? <div className="p-5"><Empty icon={ShieldCheck} title="No posted ledger balance" copy="A prepared journal is not a balance. The balance appears only after an independent posting decision." /></div> : <div className="divide-y">{balancesQuery.data.map(balance => <div key={`${balance.accountId}-${balance.currency}`} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate text-sm font-extrabold">{balance.accountCode} · {balance.accountName}</p><p className="mt-1 text-xs text-muted-foreground">{balance.accountClass} · normal {balance.normalBalance}</p></div><p className="money text-sm font-extrabold">{formatMoney(balance.balanceMinor, balance.currency)}</p></div>)}</div>}</section><section className="rounded-3xl border bg-teal-100 bg-teal-50/40 p-5"><ShieldCheck className="size-5 text-teal-700" /><h2 className="mt-4 font-extrabold">What this ledger does not do</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">It does not mark an invoice paid, change a receivable, reconcile evidence, value inventory, create an opening balance, or close the open variance. Those controls remain separate by design.</p></section></div></section>
  </div>;
}
