import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useControlScope } from "@/contexts/ControlScopeContext";
import { formatMoney } from "@/lib/control";
import { trpc } from "@/lib/trpc";
import { Boxes, ClipboardCheck, FilePlus2, PackagePlus, ReceiptText, Truck, Warehouse } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const makeKey = () => crypto.randomUUID();
const canManageStock = (role: string) => ["owner", "controller", "manager"].includes(role);

function PageHeading({ action }: { action?: React.ReactNode }) {
  return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-teal-700">Release 2 · operating facts</p><h1 className="mt-2 text-2xl font-extrabold tracking-tight sm:text-3xl">Operations desk</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Set up what you sell, record stock receipts, confirm what left the branch, then issue a linked invoice. Each step is scoped, attributable, and visible for review.</p></div>{action}</div>;
}

function Empty({ icon: Icon, title, copy }: { icon: typeof Boxes; title: string; copy: string }) {
  return <div className="rounded-3xl border border-dashed bg-white/70 px-5 py-8 text-center"><div className="mx-auto grid size-10 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Icon className="size-5" /></div><p className="mt-3 text-sm font-extrabold">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-muted-foreground">{copy}</p></div>;
}

function FirstOperatingRun() {
  return <section className="rounded-3xl border border-teal-100 bg-teal-50/45 p-5 sm:p-6"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-2xl bg-white text-teal-700 shadow-sm"><ClipboardCheck className="size-5" /></div><div><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-teal-800">First branch setup</p><h2 className="mt-1 text-lg font-extrabold">Start with the item, not an invoice.</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-700">Create a real product first. Each later action becomes available only when its supporting fact exists, so stock and debt cannot be invented by skipping steps.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><PackagePlus className="size-4 text-teal-700" /><p className="mt-2 text-sm font-extrabold">1. Add product</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Use the Product action above to define what this branch sells.</p></div><div className="rounded-2xl border bg-white p-4"><Warehouse className="size-4 text-violet-700" /><p className="mt-2 text-sm font-extrabold">2. Receive stock</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Record only what physically reaches the branch.</p></div><div className="rounded-2xl border bg-white p-4"><Truck className="size-4 text-amber-700" /><p className="mt-2 text-sm font-extrabold">3. Order, deliver, invoice</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A delivery writes stock-out; only then can a new receivable be issued.</p></div></div></section>;
}

function ProductDialog() {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const create = trpc.release2.products.create.useMutation({ onSuccess: () => { toast.success("Product added to this branch."); setOpen(false); utils.release2.products.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!canManageStock(scope.role)) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><PackagePlus className="mr-2 size-4" />Product</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add a sellable product</DialogTitle><DialogDescription>A product is a branch-scoped catalogue fact. It does not add stock or create an order.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ ...scope, sku: String(form.get("sku")), name: String(form.get("name")), unitOfMeasure: String(form.get("unit") || "unit"), reorderPointQuantity: String(form.get("reorder") || "0"), idempotencyKey: makeKey() }); }}><Input name="sku" required minLength={2} placeholder="SKU / stock code" /><Input name="name" required minLength={2} placeholder="Product name" /><div className="grid grid-cols-2 gap-3"><Input name="unit" defaultValue="unit" placeholder="Unit" /><Input name="reorder" inputMode="decimal" defaultValue="0" placeholder="Reorder quantity" /></div><Button disabled={create.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{create.isPending ? "Adding…" : "Add product"}</Button></form></DialogContent></Dialog>;
}

function ReceiveStockDialog({ products }: { products: Array<{ id: string; name: string; sku: string }> }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const receive = trpc.release2.inventory.receive.useMutation({ onSuccess: () => { toast.success("Stock receipt recorded. No sale or debt was changed."); setOpen(false); utils.release2.products.list.invalidate(scope); utils.release2.inventory.movements.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!canManageStock(scope.role) || !products.length) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl bg-teal-700 hover:bg-teal-800"><Warehouse className="mr-2 size-4" />Receive stock</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Record stock receipt</DialogTitle><DialogDescription>Only record stock physically received into this branch. Batch and expiry are optional but useful for controlled goods.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); receive.mutate({ ...scope, productId: String(form.get("productId")), quantity: String(form.get("quantity")), batchCode: String(form.get("batchCode") || "") || undefined, expiryAt: form.get("expiryAt") ? new Date(String(form.get("expiryAt"))) : undefined, reason: String(form.get("reason")), idempotencyKey: makeKey() }); }}><select name="productId" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="" disabled>Select product</option>{products.map(product => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select><Input name="quantity" required inputMode="decimal" placeholder="Quantity received, e.g. 24" /><div className="grid grid-cols-2 gap-3"><Input name="batchCode" placeholder="Batch / lot (optional)" /><Input name="expiryAt" type="date" /></div><Input name="reason" required minLength={3} placeholder="Receipt source / note" /><Button disabled={receive.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{receive.isPending ? "Recording…" : "Record stock receipt"}</Button></form></DialogContent></Dialog>;
}

function OrderDialog({ products }: { products: Array<{ id: string; name: string; sku: string }> }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const customers = trpc.control.customers.list.useQuery(scope); const [open, setOpen] = useState(false); const [lineCount, setLineCount] = useState(1);
  const create = trpc.release2.orders.create.useMutation({ onSuccess: () => { toast.success("Order confirmed. It has not reduced stock until delivery is confirmed."); setOpen(false); utils.release2.orders.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  if (!products.length || !customers.data?.length) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><FilePlus2 className="mr-2 size-4" />Order</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Confirm customer order</DialogTitle><DialogDescription>An order records commercial intent only. It neither reduces stock nor creates receivable debt.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const lines = Array.from({ length: lineCount }, (_, index) => ({ productId: String(form.get(`product-${index}`)), quantity: String(form.get(`quantity-${index}`)), unitPriceMinor: String(form.get(`price-${index}`)), currency: String(form.get(`currency-${index}`) || "NGN") })); create.mutate({ ...scope, customerId: String(form.get("customerId")), orderNumber: String(form.get("orderNumber")), expectedDeliveryAt: form.get("expectedDeliveryAt") ? new Date(String(form.get("expectedDeliveryAt"))) : undefined, note: String(form.get("note") || "") || undefined, lines, idempotencyKey: makeKey() }); }}><select name="customerId" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="" disabled>Select customer</option>{customers.data.map(customer => <option key={customer.id} value={customer.id}>{customer.name} · {customer.code}</option>)}</select><div className="grid grid-cols-2 gap-3"><Input name="orderNumber" required placeholder="Order number" /><Input name="expectedDeliveryAt" type="date" /></div>{Array.from({ length: lineCount }, (_, index) => <div key={index} className="grid gap-2 rounded-xl border bg-slate-50 p-3"><select name={`product-${index}`} required className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="" disabled>Select product</option>{products.map(product => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select><div className="grid grid-cols-3 gap-2"><Input name={`quantity-${index}`} required inputMode="decimal" placeholder="Qty" /><Input name={`price-${index}`} required inputMode="numeric" placeholder="Unit kobo" /><Input name={`currency-${index}`} required defaultValue="NGN" maxLength={3} /></div></div>)}<div className="flex items-center justify-between"><Button type="button" variant="ghost" className="text-xs" onClick={() => setLineCount(count => Math.min(count + 1, 10))}>Add line</Button>{lineCount > 1 ? <Button type="button" variant="ghost" className="text-xs text-rose-700" onClick={() => setLineCount(count => count - 1)}>Remove line</Button> : null}</div><Input name="note" placeholder="Order note (optional)" /><Button disabled={create.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{create.isPending ? "Confirming…" : "Confirm order"}</Button></form></DialogContent></Dialog>;
}

function DeliveryDialog({ orders }: { orders: Array<{ id: string; orderNumber: string; status: string }> }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false); const [orderId, setOrderId] = useState("");
  const orderLines = trpc.release2.orders.lines.useQuery({ ...scope, orderId }, { enabled: Boolean(orderId) });
  const create = trpc.release2.deliveries.create.useMutation({ onSuccess: () => { toast.success("Delivery confirmed and stock-out movements recorded together."); setOpen(false); setOrderId(""); utils.release2.deliveries.list.invalidate(scope); utils.release2.orders.list.invalidate(scope); utils.release2.products.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  const candidates = orders.filter(order => order.status === "confirmed");
  if (!canManageStock(scope.role) || !candidates.length) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><Truck className="mr-2 size-4" />Delivery</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Confirm full delivery</DialogTitle><DialogDescription>This controlled action records delivery proof and writes stock-out movements atomically. Partial delivery is intentionally deferred until its own acceptance rule is implemented.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); if (!orderLines.data?.length) return; const form = new FormData(event.currentTarget); create.mutate({ ...scope, orderId, deliveryNumber: String(form.get("deliveryNumber")), recipientName: String(form.get("recipientName") || "") || undefined, note: String(form.get("note") || "") || undefined, deliveredAt: new Date(String(form.get("deliveredAt"))), lines: orderLines.data.map(line => ({ productId: line.productId, quantity: String(line.quantity) })), idempotencyKey: makeKey() }); }}><select value={orderId} onChange={event => setOrderId(event.target.value)} required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="">Select confirmed order</option>{candidates.map(order => <option key={order.id} value={order.id}>{order.orderNumber}</option>)}</select>{orderId ? <div className="rounded-xl border bg-slate-50 p-3 text-xs text-muted-foreground">{orderLines.isLoading ? "Loading order lines…" : orderLines.data?.map(line => <p key={line.id} className="py-1">{line.productId.slice(0, 8)} · {String(line.quantity)} units</p>)}</div> : null}<div className="grid grid-cols-2 gap-3"><Input name="deliveryNumber" required placeholder="Delivery number" /><Input name="deliveredAt" required type="datetime-local" /></div><Input name="recipientName" placeholder="Receiving person (optional)" /><Input name="note" placeholder="Delivery note (optional)" /><Button disabled={!orderLines.data?.length || create.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{create.isPending ? "Confirming…" : "Confirm delivery"}</Button></form></DialogContent></Dialog>;
}

function InvoiceDialog({ orders }: { orders: Array<{ id: string; orderNumber: string; status: string }> }) {
  const scope = useControlScope(); const utils = trpc.useUtils(); const [open, setOpen] = useState(false);
  const issue = trpc.release2.invoices.issue.useMutation({ onSuccess: () => { toast.success("Invoice and new receivable obligation issued together."); setOpen(false); utils.release2.invoices.list.invalidate(scope); utils.control.obligations.list.invalidate(scope); utils.release2.orders.list.invalidate(scope); }, onError: error => toast.error(error.message) });
  const candidates = orders.filter(order => order.status === "delivered"); if (!canManageStock(scope.role) || !candidates.length) return null;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><ReceiptText className="mr-2 size-4" />Invoice</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Issue linked invoice</DialogTitle><DialogDescription>The invoice total is derived from the confirmed order lines. A fresh receivable obligation is created; no existing debt is changed.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); issue.mutate({ ...scope, orderId: String(form.get("orderId")), invoiceNumber: String(form.get("invoiceNumber")), dueAt: form.get("dueAt") ? new Date(String(form.get("dueAt"))) : undefined, idempotencyKey: makeKey() }); }}><select name="orderId" required className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="" disabled>Select delivered order</option>{candidates.map(order => <option key={order.id} value={order.id}>{order.orderNumber}</option>)}</select><Input name="invoiceNumber" required placeholder="Invoice number" /><Input name="dueAt" type="date" /><Button disabled={issue.isPending} className="rounded-xl bg-teal-700 hover:bg-teal-800">{issue.isPending ? "Issuing…" : "Issue invoice & receivable"}</Button></form></DialogContent></Dialog>;
}

export default function OperationsPage() {
  const scope = useControlScope(); const productQuery = trpc.release2.products.list.useQuery(scope); const ordersQuery = trpc.release2.orders.list.useQuery(scope); const deliveriesQuery = trpc.release2.deliveries.list.useQuery(scope); const invoicesQuery = trpc.release2.invoices.list.useQuery(scope);
  const products = productQuery.data ?? []; const orders = ordersQuery.data ?? [];
  const failedQuery = [productQuery, ordersQuery, deliveriesQuery, invoicesQuery].find(query => query.isError);
  if (failedQuery?.isError) return <div className="mx-auto max-w-3xl space-y-6"><PageHeading /><section className="rounded-3xl border bg-white p-7 text-center shadow-sm"><p className="text-sm font-extrabold text-rose-700">The operations desk could not load this scoped branch.</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{failedQuery.error.message}</p><Button className="mt-5 rounded-xl" variant="outline" onClick={() => { productQuery.refetch(); ordersQuery.refetch(); deliveriesQuery.refetch(); invoicesQuery.refetch(); }}>Try again</Button></section></div>;
  const isFirstRun = !products.length && !orders.length && !deliveriesQuery.data?.length && !invoicesQuery.data?.length;
  return <div className="mx-auto max-w-7xl space-y-6"><PageHeading action={<div className="flex flex-wrap gap-2"><ProductDialog /><ReceiveStockDialog products={products} /><OrderDialog products={products} /><DeliveryDialog orders={orders} /><InvoiceDialog orders={orders} /></div>} />
    {isFirstRun ? <FirstOperatingRun /> : <section className="grid gap-4 md:grid-cols-3"><article className="rounded-3xl border bg-white p-5 shadow-sm"><Boxes className="size-5 text-teal-700" /><p className="mt-4 text-2xl font-extrabold">{products.length}</p><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Branch products</p></article><article className="rounded-3xl border bg-white p-5 shadow-sm"><ClipboardCheck className="size-5 text-violet-700" /><p className="mt-4 text-2xl font-extrabold">{orders.filter(order => order.status === "confirmed").length}</p><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Awaiting delivery</p></article><article className="rounded-3xl border bg-white p-5 shadow-sm"><ReceiptText className="size-5 text-amber-700" /><p className="mt-4 text-2xl font-extrabold">{invoicesQuery.data?.length ?? 0}</p><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Linked invoices</p></article></section>}
    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-extrabold">Products & available stock</h2><p className="mt-1 text-xs text-muted-foreground">Derived from append-only receipts, deliveries, and transfers.</p></div></div>{productQuery.isLoading ? <p className="p-5 text-sm text-muted-foreground">Loading products…</p> : !products.length ? <div className="p-5"><Empty icon={Boxes} title="No products in this branch" copy="Add the items you sell before receiving stock or confirming orders." /></div> : <div className="divide-y">{products.map(product => <article key={product.id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate text-sm font-extrabold">{product.name}</p><p className="mt-1 text-xs text-muted-foreground">{product.sku} · reorder point {String(product.reorderPointQuantity)} {product.unitOfMeasure}</p></div><div className={`rounded-xl px-3 py-2 text-right ${product.lowStock ? "bg-amber-50 text-amber-950" : "bg-teal-50 text-teal-950"}`}><p className="text-sm font-extrabold">{product.availableQuantity}</p><p className="text-[10px] font-bold uppercase tracking-wider">available</p></div></article>)}</div>}</div>
      <div className="space-y-6"><section className="rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Latest deliveries</h2><p className="mt-1 text-xs text-muted-foreground">Stock only leaves on confirmed delivery.</p></div>{!deliveriesQuery.data?.length ? <div className="p-5"><Empty icon={Truck} title="No confirmed deliveries" copy="Create an order and receive stock before confirming the first delivery." /></div> : <div className="divide-y">{deliveriesQuery.data.slice(0, 5).map(delivery => <div key={delivery.id} className="p-4"><div className="flex justify-between gap-3"><p className="text-sm font-extrabold">{delivery.deliveryNumber}</p><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-extrabold uppercase text-emerald-800">{delivery.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{new Date(delivery.deliveredAt).toLocaleString()}</p></div>)}</div>}</section><section className="rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Latest invoices</h2><p className="mt-1 text-xs text-muted-foreground">Every invoice creates a new linked receivable.</p></div>{!invoicesQuery.data?.length ? <div className="p-5"><Empty icon={ReceiptText} title="No Release 2 invoices" copy="Issue only after a confirmed delivery; existing Release 1 receivables stay untouched." /></div> : <div className="divide-y">{invoicesQuery.data.slice(0, 5).map(invoice => <div key={invoice.id} className="flex justify-between gap-3 p-4"><div><p className="text-sm font-extrabold">{invoice.invoiceNumber}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(invoice.issuedAt).toLocaleDateString()}</p></div><p className="money text-sm font-bold">{formatMoney(String(invoice.amountMinor), invoice.currency)}</p></div>)}</div>}</section></div></section>
  </div>;
}
