import { BadgeCheck, ClipboardCheck, FlaskConical, LockKeyhole, PackageCheck, ShieldAlert, Stethoscope } from "lucide-react";
import React from "react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const approvalChecks = [
  "A licensed pharmacist reviews the source order and applicable legal or clinical requirements.",
  "The pharmacist verifies that the proposed batch is eligible, in date, correctly stored, and available in the intended branch.",
  "The approval record captures the approving pharmacist, time, decision, and any exception basis before supply can be considered.",
];

const batchSteps = [
  { title: "Receive", copy: "Capture medicine, supplier, batch, quantity, expiry, and storage condition as a controlled stock receipt." },
  { title: "Review", copy: "Propose only batches that meet the configured expiry and quarantine rules; the pharmacist retains judgement." },
  { title: "Trace", copy: "Link an authorised supply event to the approved batch, actor, timestamp, and audit correlation." },
];

export default function PharmacyPrototypePage() {
  const [showChecks, setShowChecks] = useState(false);

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 rounded-[2rem] border border-violet-100 bg-gradient-to-br from-[#15152b] via-[#1d1a3d] to-[#273260] p-6 text-white shadow-sm sm:p-8 lg:flex-row lg:items-end lg:justify-between">
      <div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white/12 px-3 py-1 text-[10px] font-extrabold uppercase tracking-[0.14em] text-violet-100">Pharmacy extension · prototype</span><span className="rounded-full border border-amber-200/25 bg-amber-300/10 px-3 py-1 text-[10px] font-extrabold uppercase tracking-[0.14em] text-amber-100">No dispensing enabled</span></div><h1 className="mt-4 text-2xl font-extrabold tracking-tight sm:text-3xl">Pharmacist approval before any batch can move.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-violet-100/80">A design preview for a future pharmacy pack. It shows the intended approval and batch-traceability sequence only. It does not store a prescription, patient record, batch, approval, sale, or stock movement.</p></div>
      <div className="flex items-center gap-3 rounded-2xl border border-white/12 bg-white/8 p-4 backdrop-blur"><div className="grid size-10 place-items-center rounded-xl bg-violet-200 text-violet-950"><ShieldAlert className="size-5" /></div><div><p className="text-xs font-extrabold">Safety boundary</p><p className="mt-1 text-xs leading-5 text-violet-100/80">People decide. The prototype cannot approve or supply.</p></div></div>
    </header>

    <section aria-label="Prototype control boundary" className="rounded-3xl border border-amber-200 bg-amber-50/80 p-5"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-2xl bg-white text-amber-700 shadow-sm"><LockKeyhole className="size-5" /></div><div><p className="text-sm font-extrabold text-amber-950">Illustrative workflow only</p><p className="mt-1 max-w-4xl text-sm leading-6 text-amber-900/80">No live customer, patient, medicine, prescription, controlled-medicine register, stock, or financial data is read or written here. A production dispensing flow must be pharmacist-led, legally configured, and separately validated before any supply action is available.</p></div></div></section>

    <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-6">
        <article className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b px-5 py-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-violet-700">Illustrative request</p><h2 className="mt-1 text-lg font-extrabold">Supply review · not submitted</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">The final product will keep preparation, pharmacist review, and eventual supply as distinct, accountable stages.</p></div><span className="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-slate-600">Draft pattern</span></div>
          <div className="grid gap-4 p-5 sm:grid-cols-3"><div className="rounded-2xl border border-violet-100 bg-violet-50/50 p-4"><ClipboardCheck className="size-5 text-violet-700" /><p className="mt-3 text-sm font-extrabold">1. Prepare</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Capture the authorised source and proposed medicine lines without reducing stock.</p></div><div className="rounded-2xl border border-amber-100 bg-amber-50/55 p-4"><Stethoscope className="size-5 text-amber-700" /><p className="mt-3 text-sm font-extrabold">2. Pharmacist review</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Record the human decision and reason before a supply event is even eligible.</p></div><div className="rounded-2xl border border-teal-100 bg-teal-50/55 p-4"><PackageCheck className="size-5 text-teal-700" /><p className="mt-3 text-sm font-extrabold">3. Trace batch</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Use an approved batch, then preserve the actor and evidence trail.</p></div></div>
        </article>

        <article className="rounded-3xl border bg-white shadow-sm"><div className="flex items-start justify-between gap-4 border-b px-5 py-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-teal-700">Illustrative batch candidate</p><h2 className="mt-1 text-lg font-extrabold">Batch traceability card</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Static prototype values below are not inventory and cannot be selected or reserved.</p></div><FlaskConical className="size-5 text-teal-700" /></div>
          <dl className="grid gap-4 p-5 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><dt className="text-[10px] font-extrabold uppercase tracking-wider text-muted-foreground">Stock item</dt><dd className="mt-1 text-sm font-extrabold">Illustrative medicine pack</dd><p className="mt-1 text-xs text-muted-foreground">Training-only placeholder · no clinical instruction</p></div><div className="rounded-2xl bg-slate-50 p-4"><dt className="text-[10px] font-extrabold uppercase tracking-wider text-muted-foreground">Batch reference</dt><dd className="mt-1 font-mono text-sm font-extrabold">BATCH-EXAMPLE-0426</dd><p className="mt-1 text-xs text-muted-foreground">Example identifier only</p></div><div className="rounded-2xl bg-slate-50 p-4"><dt className="text-[10px] font-extrabold uppercase tracking-wider text-muted-foreground">Expiry rule</dt><dd className="mt-1 text-sm font-extrabold">Verify before approval</dd><p className="mt-1 text-xs text-muted-foreground">Actual expiry threshold comes from a configured policy.</p></div><div className="rounded-2xl bg-slate-50 p-4"><dt className="text-[10px] font-extrabold uppercase tracking-wider text-muted-foreground">Storage status</dt><dd className="mt-1 text-sm font-extrabold">Confirm at review</dd><p className="mt-1 text-xs text-muted-foreground">The product rule and receipt evidence determine eligibility.</p></div></dl>
        </article>
      </div>

      <div className="space-y-6">
        <article className="rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-5"><div className="flex items-center gap-2"><BadgeCheck className="size-5 text-violet-700" /><div><h2 className="font-extrabold">Pharmacist approval gate</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">This gate will be a separate, attributed decision—not a cashier action and not an AI action.</p></div></div></div><div className="p-5"><Button variant="outline" className="w-full rounded-xl border-violet-200 text-violet-800 hover:bg-violet-50" onClick={() => setShowChecks(visible => !visible)}>{showChecks ? "Hide required review checks" : "Show required review checks"}</Button>{showChecks ? <ol className="mt-4 space-y-3" aria-label="Required pharmacist review checks">{approvalChecks.map((check, index) => <li key={check} className="flex gap-3 rounded-2xl bg-violet-50/60 p-3 text-sm leading-6 text-slate-700"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-white text-xs font-extrabold text-violet-700 shadow-sm">{index + 1}</span><span>{check}</span></li>)}</ol> : null}<Button disabled className="mt-5 w-full rounded-xl bg-slate-900 font-extrabold">Pharmacist approval is not enabled</Button><p className="mt-3 text-center text-xs leading-5 text-muted-foreground">Disabled by design: this prototype cannot capture approval, reserve a batch, or record supply.</p></div></article>

        <article className="rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-5"><h2 className="font-extrabold">Batch control sequence</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">The production module will derive availability from append-only stock events, not editable totals.</p></div><div className="divide-y">{batchSteps.map((step, index) => <div key={step.title} className="flex gap-3 p-5"><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-teal-50 text-xs font-extrabold text-teal-700">0{index + 1}</span><div><p className="text-sm font-extrabold">{step.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{step.copy}</p></div></div>)}</div></article>
      </div>
    </section>
  </div>;
}
